// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD54slrGNSR_8DRWBAuk--y-20kJwWkWgM',
    appId: '1:877939786530:web:913239d348294c61b4db7b',
    messagingSenderId: '877939786530',
    projectId: 'subtaqi',
    authDomain: 'subtaqi.firebaseapp.com',
    storageBucket: 'subtaqi.firebasestorage.app',
    measurementId: 'G-T5CLB8PMQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXBs-mVe_FxoLlZqUTLwj8IG9Nhmcm32I',
    appId: '1:877939786530:android:24e74db8c840a849b4db7b',
    messagingSenderId: '877939786530',
    projectId: 'subtaqi',
    storageBucket: 'subtaqi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUPpQjJ3ZROhHnaReSIgII4-NY4d2ExjY',
    appId: '1:877939786530:ios:269132c0ca970b35b4db7b',
    messagingSenderId: '877939786530',
    projectId: 'subtaqi',
    storageBucket: 'subtaqi.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUPpQjJ3ZROhHnaReSIgII4-NY4d2ExjY',
    appId: '1:877939786530:ios:269132c0ca970b35b4db7b',
    messagingSenderId: '877939786530',
    projectId: 'subtaqi',
    storageBucket: 'subtaqi.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD54slrGNSR_8DRWBAuk--y-20kJwWkWgM',
    appId: '1:877939786530:web:b4353a491d73e6b0b4db7b',
    messagingSenderId: '877939786530',
    projectId: 'subtaqi',
    authDomain: 'subtaqi.firebaseapp.com',
    storageBucket: 'subtaqi.firebasestorage.app',
    measurementId: 'G-VJYF8KPJ96',
  );
}
